### ISSUE TITLE
spelieve-backend-placeのバグ

### ISSUE THREAD

**Issue by Ayato-kosaka** [Ayato-kosaka/spelieve-backend-place#10]
ChIJD4CMmg1cGGARaEcYbfRRgSkでPOSTすると以下のエラーになる

```
TypeError: Cannot read properties of undefined (reading 'slice')
    at PBL002UpsertPlaceDataService.doExecute (/.../Spelive/spelieve-backend-place/src/PBL002UpsertPlaceData/PBL002UpsertPlaceData.service.ts:44:36)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at /.../Documents/Spelive/spelieve-backend-place/node_modules/@nestjs/core/router/router-execution-context.js:46:28
    at /.../Documents/Spelive/spelieve-backend-place/node_modules/@nestjs/core/router/router-proxy.js:9:17
```

**Comment by Ayato-kosaka** [comment]
@Takapy1 
対応した〜
npm の google-places-web のインターフェースがバグってたみたいで騙されてた。
googlePlaceDetailsResult.photosにundifinedを考慮して直した！
